apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.app.name }}-ns
data:
  app-name: {{ .Values.app.name }}
  app-version: {{ .Values.app.version }}
  deployment-replicas: "{{ .Values.deployment.replicaCount }}"
