apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.name }}-ns
  labels:
    app: {{ .Values.app.name }}
    version: {{ .Values.app.version }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        version: {{ .Values.app.version }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
        ports:
        - containerPort: {{ .Values.deployment.port }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
        - name: APP_NAME
          value: "{{ .Values.app.name }}"
        - name: APP_VERSION  
          value: "{{ .Values.app.version }}"
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.deployment.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.deployment.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
